### ISSUE TITLE
Missing tls-opts@file?

### ISSUE THREAD

**Issue by n1nj4888** [htpcBeginner/docker-traefik#90]
Hi There,

Noticed the following line in docker-compose-t2.yml

`- --entrypoints.https.http.tls.options=tls-opts@file`

But there doesn't seem to be any file which defines tls-opts anywhere so is this line now redundant or is there a missing tls-opts file?

Thanks,

**Comment by htpcBeginner** [comment]
Thanks for pointing it out. 

Fixed: https://github.com/htpcBeginner/docker-traefik/commit/09fe127690eadadaddea49689714dac0ccb20ba0

**Comment by n1nj4888** [comment]
@htpcBeginner - I checked the commit and although it’s called “added tls-opts.yml”, it still doesn’t actually add in the missing traefik2/rules/tls-opts.yml file even though it is still referred to in the Docker compose file? 

`- --entrypoints.https.http.tls.options=tls-opts@file `

So there still seems to be an issue here?

Thanks!
